// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr7zdnx4yNdJOXY6daG0lv9CvVGsvbbxU',
    appId: '1:801680963950:web:cd3204132b2b37c42da97f',
    messagingSenderId: '801680963950',
    projectId: 'tahir-qadri-abaya-app',
    authDomain: 'tahir-qadri-abaya-app.firebaseapp.com',
    storageBucket: 'tahir-qadri-abaya-app.appspot.com',
    measurementId: 'G-E3Z4C8TJ8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb265mRAp361ek2vCWWq0ieB6FcG6y2jY',
    appId: '1:801680963950:android:9b854801f6a2f6e12da97f',
    messagingSenderId: '801680963950',
    projectId: 'tahir-qadri-abaya-app',
    storageBucket: 'tahir-qadri-abaya-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLI1Zm_RySRvsgvZXiUCZQ2k_6tq3v5w',
    appId: '1:801680963950:ios:f63320aaba2d4eec2da97f',
    messagingSenderId: '801680963950',
    projectId: 'tahir-qadri-abaya-app',
    storageBucket: 'tahir-qadri-abaya-app.appspot.com',
    iosBundleId: 'com.example.abayaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXLI1Zm_RySRvsgvZXiUCZQ2k_6tq3v5w',
    appId: '1:801680963950:ios:f63320aaba2d4eec2da97f',
    messagingSenderId: '801680963950',
    projectId: 'tahir-qadri-abaya-app',
    storageBucket: 'tahir-qadri-abaya-app.appspot.com',
    iosBundleId: 'com.example.abayaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr7zdnx4yNdJOXY6daG0lv9CvVGsvbbxU',
    appId: '1:801680963950:web:d201e88e108f88752da97f',
    messagingSenderId: '801680963950',
    projectId: 'tahir-qadri-abaya-app',
    authDomain: 'tahir-qadri-abaya-app.firebaseapp.com',
    storageBucket: 'tahir-qadri-abaya-app.appspot.com',
    measurementId: 'G-CC8CGN4QQW',
  );
}
